import 'package:flutter/material.dart' show BuildContext;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'reward_store_service.dart';

/// Builds and shares a PDF receipt after a successful reward redemption.
class RewardReceiptPdf2 {
  RewardReceiptPdf2._();

  static String _fmt(DateTime d)=>
  '${d.day.toString().padLeft(2, '0')}/'
  '${d.month.toString().padLeft(2,'0')}'
  '${d.year}'
  '${d.hour.toString().padLeft(2, '0')}:'
  '${d.minute.toString().padLeft(2, '0')}';

  static Future<void> shareReceipt(
    BuildContext context,
    RedemptionReceipt receipt,
  )async{
    final pdf = pw.Document();

    const navy  = PdfColor.fromInt(0xFF1B3A6B);
    const green = PdfColor.fromInt(0xFF8DC21F);
    const cyan  = PdfColor.fromInt(0xFF00AEEF);

    pdf.addPage(
      pw.Page(
        pageFormat:PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (ctx) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Container(
              width: double.infinity,
              padding:const pw.EdgeInsets.symmetric(horizontal: 24,vertical: 20),
              decoration: pw.BoxDecoration(
                 gradient: const pw.LinearGradient(
                  colors: [navy, cyan, green],
                  stops: [0.0, 0.55, 1.0],
                  begin:  pw.Alignment.centerLeft,
                  end:    pw.Alignment.centerRight,
                ),
                borderRadius: pw.BorderRadius.circular(12),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      'LafargeHolcim',
                      style: pw.TextStyle(
                      fontSize:   22,
                      fontWeight: pw.FontWeight.bold,
                      color:      PdfColors.white,
                      )
                    ),
                    pw.SizedBox(height: 4),
                    pw.Text(
                    'Reward Redemption Receipt',
                    style: const pw.TextStyle(
                      fontSize: 13,
                      color:    PdfColors.white,
                    ),
                  ),
                  ]
                ),
            ),

            pw.SizedBox(height: 28),

            _sectionLabel('Redemption ID'),
            pw.SizedBox(height:4),
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(12),
              decoration: pw.BoxDecoration(
                color:        const PdfColor.fromInt(0xFFF5F5F5),
                borderRadius: pw.BorderRadius.circular(8),
                border:       pw.Border.all(color: const PdfColor.fromInt(0xFFE0E0E0)),
              ),
              child: pw.Text(
                receipt.redemptionId,
                style: pw.TextStyle(
                  fontSize:   11,
                  fontWeight: pw.FontWeight.bold,
                  color:      navy,
                ),
              ),
              ),

              pw.SizedBox(height: 20),

              _sectionLabel('Salesperson'),
              pw.SizedBox(height: 8),
              _infoRow('Name' , receipt.userName),
              pw.SizedBox(height: 6),
              _infoRow('Email' , receipt.userEmail),

              pw.SizedBox(height:20),

              _sectionLabel('Redeemed Item'),
              pw.SizedBox(height: 8),
              _infoRow('Item',       receipt.item.name),
              pw.SizedBox(height: 6),
              _infoRow('Category',   receipt.item.category),
              pw.SizedBox(height: 6),
              _infoRow('Coin Cost',  '${receipt.item.coinCost} coins'),
              pw.SizedBox(height: 6),
              _infoRow('Description', receipt.item.description),

              pw.SizedBox(height: 20),
              
              _sectionLabel('Date & Time'),
              pw.SizedBox(height: 4),
              _infoRow('Redeemed At', _fmt(receipt.redeemedAt)),

              pw.Spacer(),

              pw.Divider(color:const PdfColor.fromInt(0xFFE0E0E0)),
              pw.SizedBox(height:8),
              pw.Center(
                child: pw.Text(
                  'Please Present this receipt to your manager to collect your reward',
                   style: const pw.TextStyle(
                  fontSize: 10,
                  color:    PdfColor.fromInt(0xFF757575),
                ),
                textAlign: pw.TextAlign.center,
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Center(
                  child: pw.Text(
                   'Generated by SalesQuest · LafargeHolcim',
                style: const pw.TextStyle(
                  fontSize: 9,
                  color:    PdfColor.fromInt(0xFFBDBDBD),
                ),
                  ),
                  ),
          ],
        ),
      ),
    );

    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename : 'receipt_${receipt.redemptionId.substring(0,8)}.pdf'
      );
  }

  static pw.Widget _sectionLabel(String text)=> pw.Text(
    text,
    style:pw.TextStyle(
      fontSize: 11,
      fontWeight: pw.FontWeight.bold,
      color: const PdfColor.fromInt(0xFF1B3A6B),
      ),
  );

   static pw.Widget _infoRow(String label,String value) => pw.Row(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      pw.SizedBox(
        width:90,
        child: pw.Text(
          '$label:',
          style :const pw.TextStyle(
            fontSize: 11,
            color: PdfColor.fromInt(0xFF757575),
          ),
        ),
        ),
        pw.Expanded(
          child: pw.Text(
            value,
            style: pw.TextStyle(
              fontSize: 11,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.black,
            ),
          ),
          ),
    ],
    );

}