// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1JPPfJnUJo-BsfgMBAO1dqbE-FRqARLU',
    appId: '1:85284658322:web:8d413764940cf52a031a4b',
    messagingSenderId: '85284658322',
    projectId: 'salesgameapp-cb5f8',
    authDomain: 'salesgameapp-cb5f8.firebaseapp.com',
    storageBucket: 'salesgameapp-cb5f8.firebasestorage.app',
    measurementId: 'G-JJYNGLWG7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9JJY0doa1I-5dOR6n4mphUHgM4NWuXgg',
    appId: '1:85284658322:android:f11008b0e3cfbc59031a4b',
    messagingSenderId: '85284658322',
    projectId: 'salesgameapp-cb5f8',
    storageBucket: 'salesgameapp-cb5f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEHj2aXBwJsd6O5kw9SmivctqMd5pA_as',
    appId: '1:85284658322:ios:e522e73359da393b031a4b',
    messagingSenderId: '85284658322',
    projectId: 'salesgameapp-cb5f8',
    storageBucket: 'salesgameapp-cb5f8.firebasestorage.app',
    iosBundleId: 'com.example.lafargeholcimSalesGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEHj2aXBwJsd6O5kw9SmivctqMd5pA_as',
    appId: '1:85284658322:ios:e522e73359da393b031a4b',
    messagingSenderId: '85284658322',
    projectId: 'salesgameapp-cb5f8',
    storageBucket: 'salesgameapp-cb5f8.firebasestorage.app',
    iosBundleId: 'com.example.lafargeholcimSalesGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1JPPfJnUJo-BsfgMBAO1dqbE-FRqARLU',
    appId: '1:85284658322:web:d0ed51b2d35e538b031a4b',
    messagingSenderId: '85284658322',
    projectId: 'salesgameapp-cb5f8',
    authDomain: 'salesgameapp-cb5f8.firebaseapp.com',
    storageBucket: 'salesgameapp-cb5f8.firebasestorage.app',
    measurementId: 'G-4S1JZBD13X',
  );
}
