// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web {
    final webApiKey = dotenv.env['WEBSITE_LHM_PROJECT'] ?? '';
    if (webApiKey.isEmpty) {
      throw Exception('WEBSITE_LHM_PROJECT not found in .env');
    }
    return FirebaseOptions(
      apiKey: webApiKey,
    appId: '1:864449112171:web:dd85015a25036b87e0e92e',
    messagingSenderId: '864449112171',
    projectId: 'salesquest-c24e6',
    authDomain: 'salesquest-c24e6.firebaseapp.com',
    storageBucket: 'salesquest-c24e6.firebasestorage.app',
    measurementId: 'G-0573R9RQYT',
  );
  }

  static FirebaseOptions get android {
    final androidApiKey = dotenv.env['ANDROID_LHM_PROJECT'] ?? '';
    if (androidApiKey.isEmpty) {
      throw Exception('ANDROID_LHM_PROJECT not found in .env');
    }
    return FirebaseOptions(
      apiKey: androidApiKey,
    appId: '1:864449112171:android:bfe51af132df602ae0e92e',
    messagingSenderId: '864449112171',
    projectId: 'salesquest-c24e6',
    storageBucket: 'salesquest-c24e6.firebasestorage.app',
  );
  }
  static FirebaseOptions get ios {
    // Variable name must match exactly what is in the .env file (IOS_LHM_Project with lowercase 'p')
    final iosApiKey = dotenv.env['IOS_LHM_Project'] ?? '';
    if (iosApiKey.isEmpty) {
      throw Exception('IOS_LHM_PROJECT not found in .env');
    }
    return FirebaseOptions(
      apiKey: iosApiKey,
      appId: '1:864449112171:ios:5fdc1a42884554aae0e92e',
      messagingSenderId: '864449112171',
      projectId: 'salesquest-c24e6',
    storageBucket: 'salesquest-c24e6.firebasestorage.app',
    iosBundleId: 'com.example.lafargeholcimSalesGame',
  );
}
}